name: linux_amd64_custom
description: Custom environment for Linux AMD64 with Google Chrome
packages:
  - apt-get:
      - update
      - upgrade
      - autoclean
      - autoremove
      - install
      - google-chrome-stable
